version: "3.8"
services:
  backend:
    image: "twbanana/student-management-system:29.5.2021.18.29.33"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev


