version: "3.8"
services:
  backend:
    image: "twbanana/student-management-system:21.5.2021.14.44.26"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev


