version: "3.8"
services:
  backend:
    image: "twbanana/student-management-system:17.5.2021.21.10.7"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev


