version: "3.8"
services:
  backend:
    image: "twbanana/student-management-system:20.5.2021.3.14.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev


